# Generated by Django 4.2.3 on 2023-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(help_text='Enter Bio', max_length=350, null=True),
        ),
    ]
