# Generated by Django 4.2.3 on 2023-07-11 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_remove_follow_followedid_remove_follow_followerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
